# Supported funding model platforms
funding_platforms = {
    "github": "danny-avila",
    "patreon": "PATREON_USERNAME",
    "open_collective": "OPEN_COLLECTIVE_USERNAME",
    "ko_fi": "KO_FI_USERNAME",

