name: Playwright Tests

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'
      - 'e2e/**'
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  tests_e2e:
    name: Run Playwright tests
    if: github.event.pull_request.head.repo.full_name == 'danny-avila/LibreChat'
    timeout-minutes: 60
    runs-on: ${{ matrix.platform }}
    env:
      NODE_ENV: CI
      CI: true
      SEARCH: false
      BINGAI_TOKEN: user_provided
      CHATGPT_TOKEN: user_provided
      MONGO_URI: ${{ secrets.MONGO_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      E2E_USER_EMAIL: ${{ secrets.E2E_USER_EMAIL }}
      E2E_USER_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      CREDS_KEY: ${{ secrets.CREDS_KEY }}
      CREDS_IV: ${{ secrets.CREDS_IV }}
      DOMAIN_CLIENT: ${{ secrets.DOMAIN_CLIENT }}
      DOMAIN_SERVER: ${{ secrets.DOMAIN_SERVER }}
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Skip downloading during npm install
      PLAYWRIGHT_BROWSERS_PATH: 0 # Places binaries to node_modules/@playwright/test
      TITLE_CONVO: false
    permissions:
      actions: write
    fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'danny-avila/LibreChat'
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
        id: checkout
        save-state: true

      - name: Restore check
