name: Bug Report
description: File a detailed bug report
title: "[Bug Report] - {{details.title}}"
labels: ["bug"]
properties:
  reporter:
    type: hidden
    value: "{{github.actor}}"
  title:
    type: text
    label: Title
    description: Provide a short and descriptive title for the bug report
    validations:
      required: true
  details:
    type: textarea
    label: Description
    description: Explain the problem in detail. Include what you were doing, what you expected to happen, and what actually happened.
    validations:
      required: true
  reproduction_steps:
    type: textarea
    label: Steps to Reproduce
    description: Provide clear and concise steps to reproduce the issue. This will help us verify and fix the bug.
    validations:
      required: true
  browser:
    type: multiselect
    label: Browsers
    description: Select the browser(s) where the issue is occurring
    options:
      - label: Firefox
      - label: Chrome
      - label: Safari
      - label: Microsoft Edge
      - label: Mobile (iOS)
      - label: Mobile (Android)
  logs:
    type: textarea
    label: Relevant Log Output
    description: If applicable, paste any relevant log output here. This will help us diagnose the issue.
    render: shell
  screenshots:
    type: file
    label: Screenshots
    description: If applicable, attach screenshots to help explain the problem. We accept the following formats: jpg, jpeg, png, gif
  agreement:
    type: checkbox
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our Code of Conduct.
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
