version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - mongodb
      - meilisearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/workspaces:cached
      # - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
    user: vscode
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongodb:
    container_name: chat-mongodb
    expose:
      - 27017
    image: mongo
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.5
    expose:
      - 7700
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=5c71cf56d672d009e36070b5bc5e47b743535ae55c818ae3b735bb6ebfb4ba63
    volumes:
      - ./meili_data_v1.5:/meili_data
